---
title: "fhidata"
output: rmarkdown::html_vignette
author: "Chi Zhang"
date: "2021-10-01"
vignette: >
  %\VignetteIndexEntry{fhidata}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


Information for us

```{r setup}
library(fhidata)
library(data.table)
```


# datasets 

(suggestion: maybe change a different name? distinguish dataset from functions?)

### location 

```{r}
fhidata::norway_locations_names_b2020
```


```{r}
fhidata::norway_locations_hierarchy_all_b2020
```


```{r}
fhidata::norway_locations_redistricting_b2020
```



### population

```{r}
fhidata::norway_population_by_age_b2020
fhidata::norway_population_by_age_sex_b2020
```




# functions

### location

```{r}
fhidata::norway_locations_names()
```


```{r}
fhidata::norway_locations_redistricting()
```



```{r}
fhidata::norway_locations_hierarchy(from = 'wardoslo', to = 'municip')
fhidata::norway_locations_hierarchy(from = 'municip', to = 'baregion')
fhidata::norway_locations_hierarchy(from = 'county', to = 'faregion')
```


### population

by age 

```{r}
fhidata::norway_population_by_age_cats(cats = list(c(1:10), c(11:20)))[]
fhidata::norway_population_by_age_cats(cats = list("one to ten" = c(1:10), "eleven to twenty" = c(11:20)))
fhidata::norway_population_by_age_cats(cats = list(c(1:10), c(11:20), "21+"=c(21:200)))
```

by age and sex 

```{r}
fhidata::norway_population_by_age_sex_cats(cats = list(c(1:10), c(11:20)))
```





